directories:
    data_dir: data/
    uniswap_raw_data        : data/uniswap_raw_data/
    full:
        ML_features         : data/full/ML_features/
    liquid:
        ML_features         : data/liquid/ML_features/
        ruled_based:
             ML_features    : data/liquid/ruled_based/ML_features/
        
fig_dir:
    data_exploration: figures/data_exploration/
    full:
        clustering  : figures/full/clustering/
        embedding   : figures/full/embedding/
        prediction  : figures/full/prediction/
    liquid:
        clustering  : figures/liquid/clustering/
        embedding   : figures/liquid/embedding/
        prediction  : figures/liquid/prediction/

files: 
    all_cycles      : data/cycles_in_Uniswap.json
    filtered_cycles : data/filtered_cycles.json
    full:
        cycle_ids                   : data/full/ML_features/cycle_ids.npy
        preprocessed_data           : data/full/uniswap_data.csv
        ae_test_features               : data/full/ML_features/ae_test_features.csv
        ae_train_features              : data/full/ML_features/ae_train_features.csv
        scaled_ae_test_features        : data/full/ML_features/scaled_ae_test_features.npy
        scaled_ae_train_features       : data/full/ML_features/scaled_ae_train_features.npy
        test_ids                    : data/full/ML_features/test_ids.npy
        train_ids                   : data/full/ML_features/train_ids.npy
        encoded_test_features       : data/full/ML_features/encoded_test_features.npy
        encoded_train_features      : data/full/ML_features/encoded_train_features.npy
        additional_features_train   : data/full/additional_features_train.csv
        additional_features_test    : data/full/additional_features_test.csv
    liquid:
        preprocessed_data           : data/liquid/uniswap_data_liquid.csv    
        ae_test_features               : data/liquid/ML_features/ae_test_features_liquid.csv
        ae_train_features              : data/liquid/ML_features/ae_train_features_liquid.csv
        scaled_ae_test_features               : data/liquid/ML_features/scaled_ae_test_features_liquid.npy
        scaled_ae_train_features              : data/liquid/ML_features/scaled_ae_train_features_liquid.npy
        test_ids                    : data/liquid/ML_features/test_ids_liquid.npy
        train_ids                   : data/liquid/ML_features/train_ids_liquid.npy
        encoded_test_features       : data/liquid/ML_features/encoded_test_features_liquid.npy
        encoded_train_features      : data/liquid/ML_features/encoded_train_features_liquid.npy
        additional_features_train   : data/liquid/additional_features_train_liquid.csv
        additional_features_test    : data/liquid/additional_features_test_liquid.csv
        rule_based:
            encoded_test_features   : data/liquid/rule_based/ML_features/encoded_test_features_liquid_rule_based.csv
            encoded_train_features  : data/liquid/rule_based/ML_features/encoded_train_features_liquid_rule_based.csv
            scaled_encoded_test_features   : data/liquid/rule_based/ML_features/scaled_encoded_test_features_liquid_rule_based.npy
            scaled_encoded_train_features  : data/liquid/rule_based/ML_features/scaled_encoded_train_features_liquid_rule_based.npy
    
biquery:
    API_KEY1: BQYd6qf95gjz6MU3FTP9yQegkGVkuQ4r # Augustin's KEY
    API_KEY2: BQYt1q57Typ8HsY7nxzqsGzmKA0u7FzS # Lucas's KEY
    
models:
    autoencoder: models/embedding/autoencoder/results/
    
