directories:
    data_dir: data/
    uniswap_raw_data : data/uniswap_raw_data/
    ML_features : data/ML_features/
        
fig_dir:
    clustering: figures/clustering/
    data_exploration: figures/data_exploration/
    embedding: figures/embedding/

files: 
    cycles_in_Uniswap : data/cycles_in_Uniswap.json
    preprocessed_data: data/uniswap_data.csv
    raw_test_features  : data/ML_features/raw_test_features.npy
    raw_train_features : data/ML_features/raw_train_features.npy
    test_ids  : data/ML_features/test_ids.npy
    train_ids : data/ML_features/train_ids.npy
    encoded_test_features  : data/ML_features/encoded_test_features.npy
    encoded_train_features : data/ML_features/encoded_train_features.npy
    cycle_ids : data/ML_features/cycle_ids.npy
    all_cycles : data/cycles_in_Uniswap.json
    filtered_cycles : data/filtered_cycles.json
    additional_features : data/addional_features.csv
    additional_features_train : data/additional_features_train.csv
    additional_features_test : data/additional_features_test.csv
    
    
biquery:
    API_KEY1: BQYd6qf95gjz6MU3FTP9yQegkGVkuQ4r # Augustin's KEY
    API_KEY2: BQYt1q57Typ8HsY7nxzqsGzmKA0u7FzS # Lucas's KEY
    
models:
    autoencoder: models/embedding/autoencoder/results/
